#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBinProjekt
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyDB")]
	public partial class MyContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertLieferanten_Lagertool(Lieferanten_Lagertool instance);
    partial void UpdateLieferanten_Lagertool(Lieferanten_Lagertool instance);
    partial void DeleteLieferanten_Lagertool(Lieferanten_Lagertool instance);
    partial void InsertorgLieferanten(orgLieferanten instance);
    partial void UpdateorgLieferanten(orgLieferanten instance);
    partial void DeleteorgLieferanten(orgLieferanten instance);
    #endregion
		
		public MyContextDataContext() : 
				base(global::DBinProjekt.Properties.Settings.Default.MyDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Lieferanten_Lagertool> Lieferanten_Lagertool
		{
			get
			{
				return this.GetTable<Lieferanten_Lagertool>();
			}
		}
		
		public System.Data.Linq.Table<orgLieferanten> orgLieferanten
		{
			get
			{
				return this.GetTable<orgLieferanten>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lieferanten_Lagertool")]
	public partial class Lieferanten_Lagertool : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dbbestand;
		
		private string _lifnr;
		
		private string _ext_lifnr;
		
		private System.Nullable<decimal> _srventg;
		
		private System.Nullable<int> _konsivertrag;
		
		private string _kommentar;
		
		private System.Nullable<int> _uebart;
		
		private string _standarddrucker;
		
		private System.Nullable<bool> _format_pdf;
		
		private System.Nullable<bool> _format_file;
		
		private string _format_fileformat;
		
		private string _format_file_ext;
		
		private string _format_mask;
		
		private string _ftp_server;
		
		private string _email_an;
		
		private string _email_von;
		
		private System.Nullable<int> _konsi_erstellung_art;
		
		private System.Nullable<decimal> _srventg_alt;
		
		private System.Nullable<bool> _bestellungen_vereinzeln;
		
		private System.Nullable<bool> _statistik_senden;
		
		private System.Nullable<int> _lieferzeit_lager;
		
		private System.Nullable<int> _lieferzeit_haus;
		
		private System.Nullable<decimal> _mindestauftragswert;
		
		private System.Nullable<decimal> _mindermengenzuschlag;
		
		private string _kommentarreferenz;
		
		private System.Nullable<int> _konsistatistik_split;
		
		private System.Nullable<int> _arzneimittel_genehmigung;
		
		private System.Nullable<bool> _aktiv;
		
		private System.Nullable<bool> _MCKonsiversendung;
		
		private System.Nullable<bool> _beschaffungslieferant;
		
		private string _MoeglicheBeschaffungsarten;
		
		private string _LieferzeitenLZ;
		
		private string _BestellannahmeLief;
		
		private System.Nullable<bool> _GefahrstoffeLief;
		
		private EntityRef<orgLieferanten> _orgLieferanten;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndbbestandChanging(string value);
    partial void OndbbestandChanged();
    partial void OnlifnrChanging(string value);
    partial void OnlifnrChanged();
    partial void Onext_lifnrChanging(string value);
    partial void Onext_lifnrChanged();
    partial void OnsrventgChanging(System.Nullable<decimal> value);
    partial void OnsrventgChanged();
    partial void OnkonsivertragChanging(System.Nullable<int> value);
    partial void OnkonsivertragChanged();
    partial void OnkommentarChanging(string value);
    partial void OnkommentarChanged();
    partial void OnuebartChanging(System.Nullable<int> value);
    partial void OnuebartChanged();
    partial void OnstandarddruckerChanging(string value);
    partial void OnstandarddruckerChanged();
    partial void Onformat_pdfChanging(System.Nullable<bool> value);
    partial void Onformat_pdfChanged();
    partial void Onformat_fileChanging(System.Nullable<bool> value);
    partial void Onformat_fileChanged();
    partial void Onformat_fileformatChanging(string value);
    partial void Onformat_fileformatChanged();
    partial void Onformat_file_extChanging(string value);
    partial void Onformat_file_extChanged();
    partial void Onformat_maskChanging(string value);
    partial void Onformat_maskChanged();
    partial void Onftp_serverChanging(string value);
    partial void Onftp_serverChanged();
    partial void Onemail_anChanging(string value);
    partial void Onemail_anChanged();
    partial void Onemail_vonChanging(string value);
    partial void Onemail_vonChanged();
    partial void Onkonsi_erstellung_artChanging(System.Nullable<int> value);
    partial void Onkonsi_erstellung_artChanged();
    partial void Onsrventg_altChanging(System.Nullable<decimal> value);
    partial void Onsrventg_altChanged();
    partial void Onbestellungen_vereinzelnChanging(System.Nullable<bool> value);
    partial void Onbestellungen_vereinzelnChanged();
    partial void Onstatistik_sendenChanging(System.Nullable<bool> value);
    partial void Onstatistik_sendenChanged();
    partial void Onlieferzeit_lagerChanging(System.Nullable<int> value);
    partial void Onlieferzeit_lagerChanged();
    partial void Onlieferzeit_hausChanging(System.Nullable<int> value);
    partial void Onlieferzeit_hausChanged();
    partial void OnmindestauftragswertChanging(System.Nullable<decimal> value);
    partial void OnmindestauftragswertChanged();
    partial void OnmindermengenzuschlagChanging(System.Nullable<decimal> value);
    partial void OnmindermengenzuschlagChanged();
    partial void OnkommentarreferenzChanging(string value);
    partial void OnkommentarreferenzChanged();
    partial void Onkonsistatistik_splitChanging(System.Nullable<int> value);
    partial void Onkonsistatistik_splitChanged();
    partial void Onarzneimittel_genehmigungChanging(System.Nullable<int> value);
    partial void Onarzneimittel_genehmigungChanged();
    partial void OnaktivChanging(System.Nullable<bool> value);
    partial void OnaktivChanged();
    partial void OnMCKonsiversendungChanging(System.Nullable<bool> value);
    partial void OnMCKonsiversendungChanged();
    partial void OnbeschaffungslieferantChanging(System.Nullable<bool> value);
    partial void OnbeschaffungslieferantChanged();
    partial void OnMoeglicheBeschaffungsartenChanging(string value);
    partial void OnMoeglicheBeschaffungsartenChanged();
    partial void OnLieferzeitenLZChanging(string value);
    partial void OnLieferzeitenLZChanged();
    partial void OnBestellannahmeLiefChanging(string value);
    partial void OnBestellannahmeLiefChanged();
    partial void OnGefahrstoffeLiefChanging(System.Nullable<bool> value);
    partial void OnGefahrstoffeLiefChanged();
    #endregion
		
		public Lieferanten_Lagertool()
		{
			this._orgLieferanten = default(EntityRef<orgLieferanten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dbbestand", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string dbbestand
		{
			get
			{
				return this._dbbestand;
			}
			set
			{
				if ((this._dbbestand != value))
				{
					if (this._orgLieferanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndbbestandChanging(value);
					this.SendPropertyChanging();
					this._dbbestand = value;
					this.SendPropertyChanged("dbbestand");
					this.OndbbestandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lifnr", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lifnr
		{
			get
			{
				return this._lifnr;
			}
			set
			{
				if ((this._lifnr != value))
				{
					if (this._orgLieferanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlifnrChanging(value);
					this.SendPropertyChanging();
					this._lifnr = value;
					this.SendPropertyChanged("lifnr");
					this.OnlifnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ext_lifnr", DbType="Char(10)")]
		public string ext_lifnr
		{
			get
			{
				return this._ext_lifnr;
			}
			set
			{
				if ((this._ext_lifnr != value))
				{
					this.Onext_lifnrChanging(value);
					this.SendPropertyChanging();
					this._ext_lifnr = value;
					this.SendPropertyChanged("ext_lifnr");
					this.Onext_lifnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_srventg", DbType="Decimal(6,3)")]
		public System.Nullable<decimal> srventg
		{
			get
			{
				return this._srventg;
			}
			set
			{
				if ((this._srventg != value))
				{
					this.OnsrventgChanging(value);
					this.SendPropertyChanging();
					this._srventg = value;
					this.SendPropertyChanged("srventg");
					this.OnsrventgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_konsivertrag", DbType="Int")]
		public System.Nullable<int> konsivertrag
		{
			get
			{
				return this._konsivertrag;
			}
			set
			{
				if ((this._konsivertrag != value))
				{
					this.OnkonsivertragChanging(value);
					this.SendPropertyChanging();
					this._konsivertrag = value;
					this.SendPropertyChanged("konsivertrag");
					this.OnkonsivertragChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kommentar", DbType="VarChar(512)")]
		public string kommentar
		{
			get
			{
				return this._kommentar;
			}
			set
			{
				if ((this._kommentar != value))
				{
					this.OnkommentarChanging(value);
					this.SendPropertyChanging();
					this._kommentar = value;
					this.SendPropertyChanged("kommentar");
					this.OnkommentarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uebart", DbType="Int")]
		public System.Nullable<int> uebart
		{
			get
			{
				return this._uebart;
			}
			set
			{
				if ((this._uebart != value))
				{
					this.OnuebartChanging(value);
					this.SendPropertyChanging();
					this._uebart = value;
					this.SendPropertyChanged("uebart");
					this.OnuebartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standarddrucker", DbType="Char(30)")]
		public string standarddrucker
		{
			get
			{
				return this._standarddrucker;
			}
			set
			{
				if ((this._standarddrucker != value))
				{
					this.OnstandarddruckerChanging(value);
					this.SendPropertyChanging();
					this._standarddrucker = value;
					this.SendPropertyChanged("standarddrucker");
					this.OnstandarddruckerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format_pdf", DbType="Bit")]
		public System.Nullable<bool> format_pdf
		{
			get
			{
				return this._format_pdf;
			}
			set
			{
				if ((this._format_pdf != value))
				{
					this.Onformat_pdfChanging(value);
					this.SendPropertyChanging();
					this._format_pdf = value;
					this.SendPropertyChanged("format_pdf");
					this.Onformat_pdfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format_file", DbType="Bit")]
		public System.Nullable<bool> format_file
		{
			get
			{
				return this._format_file;
			}
			set
			{
				if ((this._format_file != value))
				{
					this.Onformat_fileChanging(value);
					this.SendPropertyChanging();
					this._format_file = value;
					this.SendPropertyChanged("format_file");
					this.Onformat_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format_fileformat", DbType="Char(30)")]
		public string format_fileformat
		{
			get
			{
				return this._format_fileformat;
			}
			set
			{
				if ((this._format_fileformat != value))
				{
					this.Onformat_fileformatChanging(value);
					this.SendPropertyChanging();
					this._format_fileformat = value;
					this.SendPropertyChanged("format_fileformat");
					this.Onformat_fileformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format_file_ext", DbType="Char(3)")]
		public string format_file_ext
		{
			get
			{
				return this._format_file_ext;
			}
			set
			{
				if ((this._format_file_ext != value))
				{
					this.Onformat_file_extChanging(value);
					this.SendPropertyChanging();
					this._format_file_ext = value;
					this.SendPropertyChanged("format_file_ext");
					this.Onformat_file_extChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_format_mask", DbType="Char(30)")]
		public string format_mask
		{
			get
			{
				return this._format_mask;
			}
			set
			{
				if ((this._format_mask != value))
				{
					this.Onformat_maskChanging(value);
					this.SendPropertyChanging();
					this._format_mask = value;
					this.SendPropertyChanged("format_mask");
					this.Onformat_maskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ftp_server", DbType="Char(20)")]
		public string ftp_server
		{
			get
			{
				return this._ftp_server;
			}
			set
			{
				if ((this._ftp_server != value))
				{
					this.Onftp_serverChanging(value);
					this.SendPropertyChanging();
					this._ftp_server = value;
					this.SendPropertyChanged("ftp_server");
					this.Onftp_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_an", DbType="Char(50)")]
		public string email_an
		{
			get
			{
				return this._email_an;
			}
			set
			{
				if ((this._email_an != value))
				{
					this.Onemail_anChanging(value);
					this.SendPropertyChanging();
					this._email_an = value;
					this.SendPropertyChanged("email_an");
					this.Onemail_anChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_von", DbType="Char(50)")]
		public string email_von
		{
			get
			{
				return this._email_von;
			}
			set
			{
				if ((this._email_von != value))
				{
					this.Onemail_vonChanging(value);
					this.SendPropertyChanging();
					this._email_von = value;
					this.SendPropertyChanged("email_von");
					this.Onemail_vonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_konsi_erstellung_art", DbType="Int")]
		public System.Nullable<int> konsi_erstellung_art
		{
			get
			{
				return this._konsi_erstellung_art;
			}
			set
			{
				if ((this._konsi_erstellung_art != value))
				{
					this.Onkonsi_erstellung_artChanging(value);
					this.SendPropertyChanging();
					this._konsi_erstellung_art = value;
					this.SendPropertyChanged("konsi_erstellung_art");
					this.Onkonsi_erstellung_artChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_srventg_alt", DbType="Decimal(6,3)")]
		public System.Nullable<decimal> srventg_alt
		{
			get
			{
				return this._srventg_alt;
			}
			set
			{
				if ((this._srventg_alt != value))
				{
					this.Onsrventg_altChanging(value);
					this.SendPropertyChanging();
					this._srventg_alt = value;
					this.SendPropertyChanged("srventg_alt");
					this.Onsrventg_altChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bestellungen_vereinzeln", DbType="Bit")]
		public System.Nullable<bool> bestellungen_vereinzeln
		{
			get
			{
				return this._bestellungen_vereinzeln;
			}
			set
			{
				if ((this._bestellungen_vereinzeln != value))
				{
					this.Onbestellungen_vereinzelnChanging(value);
					this.SendPropertyChanging();
					this._bestellungen_vereinzeln = value;
					this.SendPropertyChanged("bestellungen_vereinzeln");
					this.Onbestellungen_vereinzelnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statistik_senden", DbType="Bit")]
		public System.Nullable<bool> statistik_senden
		{
			get
			{
				return this._statistik_senden;
			}
			set
			{
				if ((this._statistik_senden != value))
				{
					this.Onstatistik_sendenChanging(value);
					this.SendPropertyChanging();
					this._statistik_senden = value;
					this.SendPropertyChanged("statistik_senden");
					this.Onstatistik_sendenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieferzeit_lager", DbType="Int")]
		public System.Nullable<int> lieferzeit_lager
		{
			get
			{
				return this._lieferzeit_lager;
			}
			set
			{
				if ((this._lieferzeit_lager != value))
				{
					this.Onlieferzeit_lagerChanging(value);
					this.SendPropertyChanging();
					this._lieferzeit_lager = value;
					this.SendPropertyChanged("lieferzeit_lager");
					this.Onlieferzeit_lagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieferzeit_haus", DbType="Int")]
		public System.Nullable<int> lieferzeit_haus
		{
			get
			{
				return this._lieferzeit_haus;
			}
			set
			{
				if ((this._lieferzeit_haus != value))
				{
					this.Onlieferzeit_hausChanging(value);
					this.SendPropertyChanging();
					this._lieferzeit_haus = value;
					this.SendPropertyChanged("lieferzeit_haus");
					this.Onlieferzeit_hausChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mindestauftragswert", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> mindestauftragswert
		{
			get
			{
				return this._mindestauftragswert;
			}
			set
			{
				if ((this._mindestauftragswert != value))
				{
					this.OnmindestauftragswertChanging(value);
					this.SendPropertyChanging();
					this._mindestauftragswert = value;
					this.SendPropertyChanged("mindestauftragswert");
					this.OnmindestauftragswertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mindermengenzuschlag", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> mindermengenzuschlag
		{
			get
			{
				return this._mindermengenzuschlag;
			}
			set
			{
				if ((this._mindermengenzuschlag != value))
				{
					this.OnmindermengenzuschlagChanging(value);
					this.SendPropertyChanging();
					this._mindermengenzuschlag = value;
					this.SendPropertyChanged("mindermengenzuschlag");
					this.OnmindermengenzuschlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kommentarreferenz", DbType="NVarChar(50)")]
		public string kommentarreferenz
		{
			get
			{
				return this._kommentarreferenz;
			}
			set
			{
				if ((this._kommentarreferenz != value))
				{
					this.OnkommentarreferenzChanging(value);
					this.SendPropertyChanging();
					this._kommentarreferenz = value;
					this.SendPropertyChanged("kommentarreferenz");
					this.OnkommentarreferenzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_konsistatistik_split", DbType="Int")]
		public System.Nullable<int> konsistatistik_split
		{
			get
			{
				return this._konsistatistik_split;
			}
			set
			{
				if ((this._konsistatistik_split != value))
				{
					this.Onkonsistatistik_splitChanging(value);
					this.SendPropertyChanging();
					this._konsistatistik_split = value;
					this.SendPropertyChanged("konsistatistik_split");
					this.Onkonsistatistik_splitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arzneimittel_genehmigung", DbType="Int")]
		public System.Nullable<int> arzneimittel_genehmigung
		{
			get
			{
				return this._arzneimittel_genehmigung;
			}
			set
			{
				if ((this._arzneimittel_genehmigung != value))
				{
					this.Onarzneimittel_genehmigungChanging(value);
					this.SendPropertyChanging();
					this._arzneimittel_genehmigung = value;
					this.SendPropertyChanged("arzneimittel_genehmigung");
					this.Onarzneimittel_genehmigungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aktiv", DbType="Bit")]
		public System.Nullable<bool> aktiv
		{
			get
			{
				return this._aktiv;
			}
			set
			{
				if ((this._aktiv != value))
				{
					this.OnaktivChanging(value);
					this.SendPropertyChanging();
					this._aktiv = value;
					this.SendPropertyChanged("aktiv");
					this.OnaktivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MCKonsiversendung", DbType="Bit")]
		public System.Nullable<bool> MCKonsiversendung
		{
			get
			{
				return this._MCKonsiversendung;
			}
			set
			{
				if ((this._MCKonsiversendung != value))
				{
					this.OnMCKonsiversendungChanging(value);
					this.SendPropertyChanging();
					this._MCKonsiversendung = value;
					this.SendPropertyChanged("MCKonsiversendung");
					this.OnMCKonsiversendungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschaffungslieferant", DbType="Bit")]
		public System.Nullable<bool> beschaffungslieferant
		{
			get
			{
				return this._beschaffungslieferant;
			}
			set
			{
				if ((this._beschaffungslieferant != value))
				{
					this.OnbeschaffungslieferantChanging(value);
					this.SendPropertyChanging();
					this._beschaffungslieferant = value;
					this.SendPropertyChanged("beschaffungslieferant");
					this.OnbeschaffungslieferantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoeglicheBeschaffungsarten", DbType="VarChar(50)")]
		public string MoeglicheBeschaffungsarten
		{
			get
			{
				return this._MoeglicheBeschaffungsarten;
			}
			set
			{
				if ((this._MoeglicheBeschaffungsarten != value))
				{
					this.OnMoeglicheBeschaffungsartenChanging(value);
					this.SendPropertyChanging();
					this._MoeglicheBeschaffungsarten = value;
					this.SendPropertyChanged("MoeglicheBeschaffungsarten");
					this.OnMoeglicheBeschaffungsartenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LieferzeitenLZ", DbType="VarChar(50)")]
		public string LieferzeitenLZ
		{
			get
			{
				return this._LieferzeitenLZ;
			}
			set
			{
				if ((this._LieferzeitenLZ != value))
				{
					this.OnLieferzeitenLZChanging(value);
					this.SendPropertyChanging();
					this._LieferzeitenLZ = value;
					this.SendPropertyChanged("LieferzeitenLZ");
					this.OnLieferzeitenLZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestellannahmeLief", DbType="VarChar(100)")]
		public string BestellannahmeLief
		{
			get
			{
				return this._BestellannahmeLief;
			}
			set
			{
				if ((this._BestellannahmeLief != value))
				{
					this.OnBestellannahmeLiefChanging(value);
					this.SendPropertyChanging();
					this._BestellannahmeLief = value;
					this.SendPropertyChanged("BestellannahmeLief");
					this.OnBestellannahmeLiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GefahrstoffeLief", DbType="Bit")]
		public System.Nullable<bool> GefahrstoffeLief
		{
			get
			{
				return this._GefahrstoffeLief;
			}
			set
			{
				if ((this._GefahrstoffeLief != value))
				{
					this.OnGefahrstoffeLiefChanging(value);
					this.SendPropertyChanging();
					this._GefahrstoffeLief = value;
					this.SendPropertyChanged("GefahrstoffeLief");
					this.OnGefahrstoffeLiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orgLieferanten_Lieferanten_Lagertool", Storage="_orgLieferanten", ThisKey="dbbestand,lifnr", OtherKey="dbbestand,lifnr", IsForeignKey=true)]
		public orgLieferanten orgLieferanten
		{
			get
			{
				return this._orgLieferanten.Entity;
			}
			set
			{
				orgLieferanten previousValue = this._orgLieferanten.Entity;
				if (((previousValue != value) 
							|| (this._orgLieferanten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._orgLieferanten.Entity = null;
						previousValue.Lieferanten_Lagertool.Remove(this);
					}
					this._orgLieferanten.Entity = value;
					if ((value != null))
					{
						value.Lieferanten_Lagertool.Add(this);
						this._dbbestand = value.dbbestand;
						this._lifnr = value.lifnr;
					}
					else
					{
						this._dbbestand = default(string);
						this._lifnr = default(string);
					}
					this.SendPropertyChanged("orgLieferanten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orgLieferanten")]
	public partial class orgLieferanten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dbbestand;
		
		private string _lifnr;
		
		private string _mcod1;
		
		private string _name1;
		
		private string _name2;
		
		private string _stras;
		
		private string _land1;
		
		private string _pstlz;
		
		private string _ort01;
		
		private string _telf1;
		
		private string _verkf;
		
		private string _telfx;
		
		private string _kdnr;
		
		private System.Nullable<int> _ztag1;
		
		private System.Nullable<decimal> _zprz1;
		
		private System.Nullable<int> _ztag2;
		
		private System.Nullable<decimal> _zprz2;
		
		private System.Nullable<int> _ztag3;
		
		private EntitySet<Lieferanten_Lagertool> _Lieferanten_Lagertool;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndbbestandChanging(string value);
    partial void OndbbestandChanged();
    partial void OnlifnrChanging(string value);
    partial void OnlifnrChanged();
    partial void Onmcod1Changing(string value);
    partial void Onmcod1Changed();
    partial void Onname1Changing(string value);
    partial void Onname1Changed();
    partial void Onname2Changing(string value);
    partial void Onname2Changed();
    partial void OnstrasChanging(string value);
    partial void OnstrasChanged();
    partial void Onland1Changing(string value);
    partial void Onland1Changed();
    partial void OnpstlzChanging(string value);
    partial void OnpstlzChanged();
    partial void Onort01Changing(string value);
    partial void Onort01Changed();
    partial void Ontelf1Changing(string value);
    partial void Ontelf1Changed();
    partial void OnverkfChanging(string value);
    partial void OnverkfChanged();
    partial void OntelfxChanging(string value);
    partial void OntelfxChanged();
    partial void OnkdnrChanging(string value);
    partial void OnkdnrChanged();
    partial void Onztag1Changing(System.Nullable<int> value);
    partial void Onztag1Changed();
    partial void Onzprz1Changing(System.Nullable<decimal> value);
    partial void Onzprz1Changed();
    partial void Onztag2Changing(System.Nullable<int> value);
    partial void Onztag2Changed();
    partial void Onzprz2Changing(System.Nullable<decimal> value);
    partial void Onzprz2Changed();
    partial void Onztag3Changing(System.Nullable<int> value);
    partial void Onztag3Changed();
    #endregion
		
		public orgLieferanten()
		{
			this._Lieferanten_Lagertool = new EntitySet<Lieferanten_Lagertool>(new Action<Lieferanten_Lagertool>(this.attach_Lieferanten_Lagertool), new Action<Lieferanten_Lagertool>(this.detach_Lieferanten_Lagertool));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dbbestand", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string dbbestand
		{
			get
			{
				return this._dbbestand;
			}
			set
			{
				if ((this._dbbestand != value))
				{
					this.OndbbestandChanging(value);
					this.SendPropertyChanging();
					this._dbbestand = value;
					this.SendPropertyChanged("dbbestand");
					this.OndbbestandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lifnr", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lifnr
		{
			get
			{
				return this._lifnr;
			}
			set
			{
				if ((this._lifnr != value))
				{
					this.OnlifnrChanging(value);
					this.SendPropertyChanging();
					this._lifnr = value;
					this.SendPropertyChanged("lifnr");
					this.OnlifnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mcod1", DbType="Char(25)")]
		public string mcod1
		{
			get
			{
				return this._mcod1;
			}
			set
			{
				if ((this._mcod1 != value))
				{
					this.Onmcod1Changing(value);
					this.SendPropertyChanging();
					this._mcod1 = value;
					this.SendPropertyChanged("mcod1");
					this.Onmcod1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name1", DbType="Char(35)")]
		public string name1
		{
			get
			{
				return this._name1;
			}
			set
			{
				if ((this._name1 != value))
				{
					this.Onname1Changing(value);
					this.SendPropertyChanging();
					this._name1 = value;
					this.SendPropertyChanged("name1");
					this.Onname1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name2", DbType="Char(35) NOT NULL", CanBeNull=false)]
		public string name2
		{
			get
			{
				return this._name2;
			}
			set
			{
				if ((this._name2 != value))
				{
					this.Onname2Changing(value);
					this.SendPropertyChanging();
					this._name2 = value;
					this.SendPropertyChanged("name2");
					this.Onname2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stras", DbType="Char(35)")]
		public string stras
		{
			get
			{
				return this._stras;
			}
			set
			{
				if ((this._stras != value))
				{
					this.OnstrasChanging(value);
					this.SendPropertyChanging();
					this._stras = value;
					this.SendPropertyChanged("stras");
					this.OnstrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_land1", DbType="Char(3)")]
		public string land1
		{
			get
			{
				return this._land1;
			}
			set
			{
				if ((this._land1 != value))
				{
					this.Onland1Changing(value);
					this.SendPropertyChanging();
					this._land1 = value;
					this.SendPropertyChanged("land1");
					this.Onland1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pstlz", DbType="Char(10)")]
		public string pstlz
		{
			get
			{
				return this._pstlz;
			}
			set
			{
				if ((this._pstlz != value))
				{
					this.OnpstlzChanging(value);
					this.SendPropertyChanging();
					this._pstlz = value;
					this.SendPropertyChanged("pstlz");
					this.OnpstlzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ort01", DbType="Char(35)")]
		public string ort01
		{
			get
			{
				return this._ort01;
			}
			set
			{
				if ((this._ort01 != value))
				{
					this.Onort01Changing(value);
					this.SendPropertyChanging();
					this._ort01 = value;
					this.SendPropertyChanged("ort01");
					this.Onort01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telf1", DbType="Char(50)")]
		public string telf1
		{
			get
			{
				return this._telf1;
			}
			set
			{
				if ((this._telf1 != value))
				{
					this.Ontelf1Changing(value);
					this.SendPropertyChanging();
					this._telf1 = value;
					this.SendPropertyChanged("telf1");
					this.Ontelf1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verkf", DbType="Char(30)")]
		public string verkf
		{
			get
			{
				return this._verkf;
			}
			set
			{
				if ((this._verkf != value))
				{
					this.OnverkfChanging(value);
					this.SendPropertyChanging();
					this._verkf = value;
					this.SendPropertyChanged("verkf");
					this.OnverkfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telfx", DbType="Char(50)")]
		public string telfx
		{
			get
			{
				return this._telfx;
			}
			set
			{
				if ((this._telfx != value))
				{
					this.OntelfxChanging(value);
					this.SendPropertyChanging();
					this._telfx = value;
					this.SendPropertyChanged("telfx");
					this.OntelfxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kdnr", DbType="Char(20)")]
		public string kdnr
		{
			get
			{
				return this._kdnr;
			}
			set
			{
				if ((this._kdnr != value))
				{
					this.OnkdnrChanging(value);
					this.SendPropertyChanging();
					this._kdnr = value;
					this.SendPropertyChanged("kdnr");
					this.OnkdnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ztag1", DbType="Int")]
		public System.Nullable<int> ztag1
		{
			get
			{
				return this._ztag1;
			}
			set
			{
				if ((this._ztag1 != value))
				{
					this.Onztag1Changing(value);
					this.SendPropertyChanging();
					this._ztag1 = value;
					this.SendPropertyChanged("ztag1");
					this.Onztag1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zprz1", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> zprz1
		{
			get
			{
				return this._zprz1;
			}
			set
			{
				if ((this._zprz1 != value))
				{
					this.Onzprz1Changing(value);
					this.SendPropertyChanging();
					this._zprz1 = value;
					this.SendPropertyChanged("zprz1");
					this.Onzprz1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ztag2", DbType="Int")]
		public System.Nullable<int> ztag2
		{
			get
			{
				return this._ztag2;
			}
			set
			{
				if ((this._ztag2 != value))
				{
					this.Onztag2Changing(value);
					this.SendPropertyChanging();
					this._ztag2 = value;
					this.SendPropertyChanged("ztag2");
					this.Onztag2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zprz2", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> zprz2
		{
			get
			{
				return this._zprz2;
			}
			set
			{
				if ((this._zprz2 != value))
				{
					this.Onzprz2Changing(value);
					this.SendPropertyChanging();
					this._zprz2 = value;
					this.SendPropertyChanged("zprz2");
					this.Onzprz2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ztag3", DbType="Int")]
		public System.Nullable<int> ztag3
		{
			get
			{
				return this._ztag3;
			}
			set
			{
				if ((this._ztag3 != value))
				{
					this.Onztag3Changing(value);
					this.SendPropertyChanging();
					this._ztag3 = value;
					this.SendPropertyChanged("ztag3");
					this.Onztag3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orgLieferanten_Lieferanten_Lagertool", Storage="_Lieferanten_Lagertool", ThisKey="dbbestand,lifnr", OtherKey="dbbestand,lifnr")]
		public EntitySet<Lieferanten_Lagertool> Lieferanten_Lagertool
		{
			get
			{
				return this._Lieferanten_Lagertool;
			}
			set
			{
				this._Lieferanten_Lagertool.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lieferanten_Lagertool(Lieferanten_Lagertool entity)
		{
			this.SendPropertyChanging();
			entity.orgLieferanten = this;
		}
		
		private void detach_Lieferanten_Lagertool(Lieferanten_Lagertool entity)
		{
			this.SendPropertyChanging();
			entity.orgLieferanten = null;
		}
	}
}
#pragma warning restore 1591
